"""empty message

Revision ID: 49350f9ca156
Revises: None
Create Date: 2016-07-14 11:50:25.765883

"""

# revision identifiers, used by Alembic.
revision = '49350f9ca156'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stu_number', sa.String(length=64), nullable=True),
    sa.Column('wechat_id', sa.String(length=64), nullable=True),
    sa.Column('zhengfang_password', sa.String(length=64), nullable=True),
    sa.Column('library_password', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('library_password'),
    sa.UniqueConstraint('stu_number'),
    sa.UniqueConstraint('wechat_id'),
    sa.UniqueConstraint('zhengfang_password')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    ### end Alembic commands ###
